parameters:
- name: workingDirectory
  type: string
    
jobs:
  - job: Plan
    steps:
      - checkout: self
      - task: TerraformInstaller@0
        displayName: 'install Terraform latest'
      - task: TerraformCLI@0
        displayName: 'init'
        inputs:
          command: init
          backendType: azurerm
          backendServiceArm: $(backend_service_arm)
          backendAzureRmKey: $(backend_key)
          backendAzureRmResourceGroupName: $(backend_resource_group_name)
          backendAzureRmStorageAccountName: $(backend_storage_account_name)
          backendAzureRmContainerName: $(backend_container_name)
          workingDirectory: ${{parameters.workingDirectory}}
          allowTelemetryCollection: false

      - task: TerraformCLI@0
        displayName: 'plan'
        inputs:
          command: 'plan'
          commandOptions: '-input=false -var-file="$(customer)/$(customer).tfvars"'    
          backendType: azurerm
          backendServiceArm: $(backend_service_arm)
          backendAzureRmKey: $(backend_key)
          backendAzureRmResourceGroupName: $(backend_resource_group_name)
          backendAzureRmStorageAccountName: $(backend_storage_account_name)
          backendAzureRmContainerName: $(backend_container_name)
          workingDirectory: ${{parameters.workingDirectory}}
          allowTelemetryCollection: false
        env:
          TF_VAR_azadclient_id: $(azad_client_id)
          TF_VAR_azadclient_secret: $(azad_client_secret)
          TF_VAR_azadtenant_id: $(azad_tenant_id)
          TF_VAR_client_id: $(infpaysygo_client_id)
          TF_VAR_client_secret: $(infpaysygo_client_secret)
          TF_VAR_tenant_id: $(infpaysygo_tenant_id)
          TF_VAR_subscription_id: $(infpaysygo_subscription_id)
          TF_VAR_backend_container_name: $(backend_container_name)
          TF_VAR_backend_storage_account_name: $(backend_storage_account_name)
          TF_VAR_backend_resource_group_name: $(backend_resource_group_name)
          TF_VAR_backend_key: $(backend_key)      
      
  - job: Approval
    pool: server # Agentless job
    dependsOn:
    - Plan
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |                
            'joe.tahsin@azurenative.com'
          instructions: 'Controleer de output van terraform plan in de vorige stap. Akkoord met de wijziging? Klik dan op resume.'
          onTimeout: 'reject'

  - job: Deployment
    dependsOn: 
    - Approval
    steps:
      - task: TerraformInstaller@0
        displayName: 'install Terraform latest'
      - task: TerraformCLI@0
        displayName: 'init'
        inputs:
          command: init
          backendType: azurerm
          backendServiceArm: $(backend_service_arm)
          backendAzureRmKey: $(backend_key)
          backendAzureRmResourceGroupName: $(backend_resource_group_name)
          backendAzureRmStorageAccountName: $(backend_storage_account_name)
          backendAzureRmContainerName: $(backend_container_name)
          workingDirectory: ${{parameters.workingDirectory}}
          allowTelemetryCollection: false

      - task: TerraformCLI@0
        displayName: 'apply'
        inputs:
          command: 'apply'
          commandOptions: '-input=false -var-file="$(customer)/$(customer).tfvars"'
          workingDirectory: ${{parameters.workingDirectory}}
        env:
          TF_VAR_azadclient_id: $(azad_client_id)
          TF_VAR_azadclient_secret: $(azad_client_secret)
          TF_VAR_azadtenant_id: $(azad_tenant_id)
          TF_VAR_client_id: $(infpaysygo_client_id)
          TF_VAR_client_secret: $(infpaysygo_client_secret)
          TF_VAR_tenant_id: $(infpaysygo_tenant_id)
          TF_VAR_subscription_id: $(infpaysygo_subscription_id)
          TF_VAR_backend_container_name: $(backend_container_name)
          TF_VAR_backend_storage_account_name: $(backend_storage_account_name)
          TF_VAR_backend_resource_group_name: $(backend_resource_group_name)
          TF_VAR_backend_key: $(backend_key)   