parameters:
- name: workingDirectory
  type: string
    
jobs:
  - job: Plan
    steps:
      - checkout: self
      - task: TerraformInstaller@0
        displayName: 'install Terraform latest'
      - task: TerraformCLI@0
        displayName: 'init'
        inputs:
          command: init
          backendType: azurerm
          workingDirectory: $(workingDirectory)
          backendServiceArm: azdoserviceconnection
          environmentServiceName: azdoserviceconnection
      - task: TerraformCLI@0
        displayName: 'plan'
        inputs:
          command: 'plan'
          commandOptions: '-input=false -var-file="$(customer)/$(customer).tfvars"'    
          backendType: azurerm      
          workingDirectory: $(workingDirectory)
          backendServiceArm: azdoserviceconnection
          environmentServiceName: azdoserviceconnection
        env:
          TF_VAR_azadclient_id: $(azad_client_id)
          TF_VAR_azadclient_secret: $(azad_client_secret)
          TF_VAR_azadtenant_id: $(azad_tenant_id)
          TF_VAR_client_id: $(infpaysygo_client_id)
          TF_VAR_client_secret: $(infpaysygo_client_secret)
          TF_VAR_tenant_id: $(infpaysygo_tenant_id)
          TF_VAR_subscription_id: $(infpaysygo_subscription_id)       
      
  - job: Approval
    pool: server # Agentless job
    dependsOn:
    - Plan
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |                
            'joe.tahsin@azurenative.com'
          instructions: 'Controleer de output van terraform plan in de vorige stap. Akkoord met de wijziging? Klik dan op resume.'
          onTimeout: 'reject'

  - job: Deployment
    dependsOn: 
    - Approval
    steps:
      - task: TerraformInstaller@0
        displayName: 'install Terraform latest'
      - task: TerraformCLI@0
        displayName: 'init'
        inputs:
          command: init
          backendType: azurerm
          workingDirectory: $(workingDirectory)
          backendServiceArm: azdoserviceconnection
          environmentServiceName: azdoserviceconnection
      - task: TerraformCLI@0
        displayName: 'apply'
        inputs:
          command: 'apply'
          commandOptions: '-input=false -auto-approve -var-file="$(customer)/$(customer).tfvars"'
        env:
          TF_VAR_azadclient_id: $(azad_client_id)
          TF_VAR_azadclient_secret: $(azad_client_secret)
          TF_VAR_azadtenant_id: $(azad_tenant_id)
          TF_VAR_client_id: $(infpaysygo_client_id)
          TF_VAR_client_secret: $(infpaysygo_client_secret)
          TF_VAR_tenant_id: $(infpaysygo_tenant_id)
          TF_VAR_subscription_id: $(infpaysygo_subscription_id)