parameters:
- name: workingDirectory
  type: string
    
jobs:
  - job: Plan
    steps:
      - script: terraform init
        workingDirectory: ${{parameters.workingDirectory}}
        displayName: Initialize terraform backend

      - script: terraform plan -input=false
        workingDirectory: ${{parameters.workingDirectory}}
        displayName: Plan the infrastructure
        env:
          TF_VAR_azadclient_id: $(azad_client_id)
          TF_VAR_azadclient_secret: $(azad_client_secret)
          TF_VAR_azadtenant_id: $(azad_tenant_id)
          TF_VAR_client_id: $(infpaysygo_client_id)
          TF_VAR_client_secret: $(infpaysygo_client_secret)
          TF_VAR_tenant_id: $(infpaysygo_tenant_id)
          TF_VAR_subscription_id: $(infpaysygo_subscription_id)          
      
  - job: Approval
    pool: server # Agentless job
    dependsOn:
    - Plan
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |                
            'joe.tahsin@azurenative.com'
          instructions: 'Controleer de output van terraform plan in de vorige stap. Akkoord met de wijziging? Klik dan op resume.'
          onTimeout: 'reject'

  - job: Deployment
    dependsOn: 
    - Approval
    steps:
    - script: terraform init
      workingDirectory: ${{parameters.workingDirectory}}
      displayName: Initialize terraform backend
    - script:
        terraform apply -auto-approve -input=false
      workingDirectory: ${{parameters.workingDirectory}}
      displayName: Apply the infrastructure (auto approve)
      env:
        TF_VAR_azadclient_id: $(azad_client_id)
        TF_VAR_azadclient_secret: $(azad_client_secret)
        TF_VAR_azadtenant_id: $(azad_tenant_id)
        TF_VAR_client_id: $(infpaysygo_client_id)
        TF_VAR_client_secret: $(infpaysygo_client_secret)
        TF_VAR_tenant_id: $(infpaysygo_tenant_id)
        TF_VAR_subscription_id: $(infpaysygo_subscription_id)